spring.application.name=${SPRING_APPLICATION_NAME}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
server.port=${SERVER_PORT}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}

spring.data.mongodb.auto-index-creation=${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION}

clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_SECRET_KEY}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}

# Cloudinary Configuration for Cloud File Storage
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}
cloudinary.upload.folder=${CLOUDINARY_UPLOAD_FOLDER:cloudshare}

springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH}
springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH}